### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by andyhd** [andyhd/ld42#4]
>I’d really like to play the game, but I’m not sure how to start it, I’ve downloaded the macOs zip, unzipped it and started the executable in the Terminal, but it says the following, after a window popped up for a millisec: ![screenshot](https://static.jam.vg/raw/2c2/81/z/19b50.png)

**Comment by borodust** [comment]
That's a known problem with SBCL version CI pipeline uses. I need to update this one. As a temporary workaround, you can use [CCL pipeline](https://github.com/borodust/notalone/blob/master/.travis.yml#L27-L28) like in [notalone](https://github.com/borodust/notalone) project. See `.travis.yml` and `.appveyor.yml`

**Comment by andyhd** [comment]
@borodust Thanks!
